version: '2.1'

services:

  oe-1:
    container_name: oe1
    image: ethcore/openethereum:v3.1.1
    cpus: '24'
    mem_limit: '24G'
    ports:
      - "8555:8545"
      - "30303:30303"
    volumes:
      - "./openethereum/eth1/config.toml:/home/openethereum/.local/share/openethereum/config.toml"
      - "./openethereum/openethereum.log:/var/log/openethereum.log"
      - "/mnt/eth1:/data" # Change this to reflect the data directory for your eth node
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default

  nginx:
    container_name: nginx
    image: nginx-brotli:latest
    cpus: '2'
    mem_limit: '2G'
    ports:
      - "443-444:443-444" # Where the HTTPS will terminate for your pocket nodes
    volumes:
      - "/etc/letsencrypt/live/YOURDOMAIN/fullchain.pem:/etc/nginx/fullchain.pem"
      - "/etc/letsencrypt/live/YOURDOMAIN/privkey.pem:/etc/nginx/privkey.pem"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/nodes.conf:/etc/nginx/conf.d/default.conf"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default

  node-1:
    image: pocket-core-rc-0.5.2.10:latest
    privileged: true
    command: "pocket start"
    ports:
      - "8082:8082"  #  POKT RPC
      - "26656:26656" #  Tendermint Peers
    environment:
      POCKET_CORE_KEY: "STAKED_ACCOUNT_#1_PRIVATE_KEY"
      POCKET_CORE_PASSPHRASE: "RANDOM_PASSPHRASE"
      GODEBUG: "madvdontneed=1"
    volumes:
        - "./node-shared/chains.json:/home/app/.pocket/config/chains.json"
        - "./node-shared/genesis.json:/home/app/.pocket/config/genesis.json"
        - "./node-1/auth.json:/home/app/.pocket/config/auth.json"
        - "./node-1/config.json:/home/app/.pocket/config/config.json"
        - "./node-1/data:/home/app/.pocket/data"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - pocket

  node-2:
    image: pocket-core-rc-0.5.2.10:latest
    privileged: true
    command: "pocket start"
    ports:
      - "8083:8082"  #  POKT RPC -- This one is incremented so it is also available on 8083 for nginx
      - "26666:26666" #  Tendermint Peers
    environment:
      POCKET_CORE_KEY: "STAKED_ACCOUNT_#2_PRIVATE_KEY"
      POCKET_CORE_PASSPHRASE: "RANDOM_PASSPHRASE"
      GODEBUG: "madvdontneed=1"
    volumes:
        - "./node-shared/chains.json:/home/app/.pocket/config/chains.json"
        - "./node-shared/genesis.json:/home/app/.pocket/config/genesis.json"
        - "./node-2/auth.json:/home/app/.pocket/config/auth.json"
        - "./node-2/config.json:/home/app/.pocket/config/config.json"
        - "./node-2/data:/home/app/.pocket/data"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - pocket

networks:
  pocket:
    driver: bridge
